# Generated by Django 5.2.3 on 2026-04-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("loan_officer", "Loan Officer"),
                    ("accountant", "Accountant"),
                    ("manager", "Manager"),
                ],
                default="loan_officer",
                max_length=20,
            ),
        ),
    ]
