# Generated by Django 5.2.3 on 2026-05-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("loan_officer", "Loan Officer"),
                    ("accountant", "Accountant"),
                ],
                default="loan_officer",
                max_length=20,
            ),
        ),
    ]
