# Generated by Django 5.2.3 on 2025-08-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('sum_of_years', 'Sum of Years Digits'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=50)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('useful_life_years', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('cash', 'Cash Account'), ('credit', 'Credit Account'), ('loan', 'Loan Account')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_type', models.CharField(choices=[('operational', 'Operational Expense'), ('administrative', 'Administrative Expense'), ('financial', 'Financial Expense'), ('other', 'Other Expense')], default='operational', max_length=50)),
                ('monthly_budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('operational', 'Operational Income'), ('investment', 'Investment Income'), ('other', 'Other Income')], default='operational', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_documentation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Income Source',
                'verbose_name_plural': 'Income Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20)),
                ('min_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Sector',
                'verbose_name_plural': 'Loan Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Working Mode', max_length=200)),
                ('monday_enabled', models.BooleanField(default=True)),
                ('tuesday_enabled', models.BooleanField(default=True)),
                ('wednesday_enabled', models.BooleanField(default=True)),
                ('thursday_enabled', models.BooleanField(default=True)),
                ('friday_enabled', models.BooleanField(default=True)),
                ('saturday_enabled', models.BooleanField(default=False)),
                ('sunday_enabled', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default='08:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
                ('lunch_start', models.TimeField(default='12:00:00')),
                ('lunch_end', models.TimeField(default='13:00:00')),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('Africa/Dar_es_Salaam', 'East Africa Time (Tanzania)'), ('Asia/Kolkata', 'India Standard Time'), ('Europe/London', 'Greenwich Mean Time'), ('America/New_York', 'Eastern Time')], default='Africa/Dar_es_Salaam', max_length=50)),
                ('allow_backdating', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Working Mode',
                'verbose_name_plural': 'Working Modes',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='If true, this holiday occurs every year')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['date'],
                'unique_together': {('name', 'date')},
            },
        ),
    ]


