# Generated by Django 5.2.3 on 2026-02-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_assetcategory_bankaccount_expensecategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='postal_code',
        ),
    ]
