# Generated by Django 5.2.3 on 2026-02-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_postal_code_from_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="base_currency",
            field=models.CharField(default="TZS", max_length=10),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="country",
            field=models.CharField(default="Tanzania", max_length=100),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
