# Generated by Django 5.2.3 on 2026-02-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_companyprofile_base_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="address_line_2",
        ),
    ]
