# Generated by Django 5.2.3 on 2026-04-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_branch_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="base_currency",
            field=models.CharField(default="TSH", max_length=10),
        ),
    ]
