# Generated by Django 5.2.3 on 2025-08-05 08:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_account', models.BooleanField(default=False, help_text='System-generated account')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('entry_date', models.DateField()),
                ('description', models.TextField()),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('is_reversing', models.BooleanField(default=False, help_text='Reversing entry')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]


