# Generated by Django 5.2.3 on 2026-02-15 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowers", "0001_initial"),
        ("core", "0004_alter_companyprofile_base_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="borrowers",
                to="core.branch",
            ),
        ),
        migrations.AlterField(
            model_name="borrowergroup",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="borrower_groups",
                to="core.branch",
            ),
        ),
    ]
