# Generated by Django 5.2.3 on 2025-08-05 08:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Annual interest rate as percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))])),
                ('interest_calculation_method', models.CharField(choices=[('simple', 'Simple Interest'), ('compound_monthly', 'Compound Monthly'), ('compound_quarterly', 'Compound Quarterly'), ('compound_annually', 'Compound Annually')], default='simple', max_length=20)),
                ('interest_posting_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi-Annually'), ('annually', 'Annually')], default='monthly', max_length=15)),
                ('minimum_opening_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maximum_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('maximum_deposit_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('maximum_withdrawal_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('account_maintenance_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('withdrawal_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('allow_overdraft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(editable=False, help_text='Auto-generated account number', max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance available for withdrawal (excluding holds)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('accrued_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_interest_calculation', models.DateField(blank=True, null=True)),
                ('last_interest_posting', models.DateField(blank=True, null=True)),
                ('total_interest_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='active', max_length=15)),
                ('opened_date', models.DateField(default=django.utils.timezone.now)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('closure_reason', models.TextField(blank=True, null=True)),
                ('is_dormant', models.BooleanField(default=False)),
                ('dormant_date', models.DateField(blank=True, null=True)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('total_holds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('linked_loan_id', models.CharField(blank=True, help_text='ID of loan this account is linked to', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to='borrowers.borrower')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_savings_accounts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_savings_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('savings_product', models.ForeignKey(blank=True, help_text='Savings product type for this account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='savings.savingsproduct')),
            ],
            options={
                'ordering': ['-opened_date'],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccountHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_type', models.CharField(choices=[('loan_security', 'Loan Security'), ('legal_hold', 'Legal Hold'), ('administrative', 'Administrative Hold'), ('maintenance', 'Maintenance Hold'), ('other', 'Other')], max_length=20)),
                ('hold_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField()),
                ('hold_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=15)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holds', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_holds', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='savings.savingsaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsLoanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('minimum_balance', 'Minimum Balance Required'), ('savings_period', 'Minimum Savings Period'), ('savings_ratio', 'Savings to Loan Ratio'), ('mandatory_savings', 'Mandatory Savings Before Loan')], max_length=20)),
                ('loan_type', models.CharField(help_text='Loan type this rule applies to', max_length=50)),
                ('minimum_balance_required', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_savings_period_months', models.PositiveIntegerField(blank=True, help_text='Minimum months of savings history required', null=True)),
                ('savings_to_loan_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Required savings as percentage of loan amount', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('mandatory_savings_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Grace period for rule compliance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['loan_type', 'rule_type'],
                'unique_together': {('loan_type', 'rule_type')},
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest'), ('fee', 'Fee'), ('transfer', 'Transfer')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('transaction_id', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_savings_transactions', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.savingsaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsInterestCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('average_balance', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('days_in_period', models.PositiveIntegerField()),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('journal_entry_id', models.CharField(blank=True, help_text='Reference to journal entry in general ledger', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interest_calculations', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_interest_calculations', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_calculations', to='savings.savingsaccount')),
            ],
            options={
                'ordering': ['-calculation_date'],
                'unique_together': {('savings_account', 'period_start_date', 'period_end_date')},
            },
        ),
    ]
