# Generated by Django 5.2.3 on 2026-04-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0003_rename_savingsloanrule_loan_type_to_loan_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsloanrule",
            name="loan_category",
            field=models.CharField(
                help_text="Loan category this rule applies to", max_length=50
            ),
        ),
    ]
