# Generated by Django 5.2.3 on 2025-08-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_grant_shareholder_capital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grant',
        ),
    ]


