# Generated by Django 5.2.3 on 2025-08-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0003_delete_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('loan_interest', 'Loan Interest'), ('service_fees', 'Service Fees'), ('membership_fees', 'Membership Fees'), ('investment_returns', 'Investment Returns'), ('donations', 'Donations'), ('other', 'Other Income')], max_length=20),
        ),
    ]


