# Generated by Django 5.2.3 on 2026-05-26 21:56

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


def migrate_sources(apps, schema_editor):
    Income = apps.get_model('finance_tracker', 'Income')
    Expenditure = apps.get_model('finance_tracker', 'Expenditure')
    IncomeSource = apps.get_model('core', 'IncomeSource')
    ExpenseCategory = apps.get_model('core', 'ExpenseCategory')

    # Helper to ensure a core record exists for a legacy code
    def ensure_income_source(code, label=None):
        if code is None:
            return None
        obj = IncomeSource.objects.filter(code=code).first()
        if obj:
            return obj
        name = label or str(code)
        return IncomeSource.objects.create(code=code, name=name)

    def ensure_expense_category(code, label=None):
        if code is None:
            return None
        obj = ExpenseCategory.objects.filter(code=code).first()
        if obj:
            return obj
        name = label or str(code)
        return ExpenseCategory.objects.create(code=code, name=name)

    # Migrate Income.source (legacy char code) -> source_new (FK)
    for inc in Income.objects.all():
        legacy = getattr(inc, 'source', None)
        if legacy:
            core_src = ensure_income_source(legacy)
            inc.source_new_id = core_src.id
            inc.save(update_fields=['source_new_id'])

    # Migrate Expenditure.expenditure_type -> expenditure_type_new
    for exp in Expenditure.objects.all():
        legacy = getattr(exp, 'expenditure_type', None)
        if legacy:
            core_cat = ensure_expense_category(legacy)
            exp.expenditure_type_new_id = core_cat.id
            exp.save(update_fields=['expenditure_type_new_id'])


def reverse_migrate_sources(apps, schema_editor):
    # No-op reverse: leave core records in place
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_companyprofile_base_currency"),
        ("finance_tracker", "0008_expenditure_rejection_reason"),
    ]

    operations = [
        # Add new FK fields to migrate data safely
        migrations.AddField(
            model_name='income',
            name='source_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.incomesource'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='expenditure_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expensecategory'),
        ),
        migrations.RunPython(migrate_sources, reverse_migrate_sources),
        # Remove old fields and rename new ones
        migrations.RemoveField(model_name='income', name='source'),
        migrations.RenameField(model_name='income', old_name='source_new', new_name='source'),
        migrations.RemoveField(model_name='expenditure', name='expenditure_type'),
        migrations.RenameField(model_name='expenditure', old_name='expenditure_type_new', new_name='expenditure_type'),
    ]
