# Generated by Django 5.2.3 on 2025-08-05 08:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_loans', to='borrowers.borrowergroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupLoanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borrowers.borrower')),
                ('group_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='loans.grouploan')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.PositiveIntegerField()),
                ('repayment_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=15)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off')], default='pending', max_length=15)),
                ('application_notes', models.TextField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='borrowers.borrower')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grouploan',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_loan', to='loans.loan'),
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursement_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_redisbursed', models.BooleanField(default=False)),
                ('disbursed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('default_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_duration_months', models.PositiveIntegerField(default=1)),
                ('max_duration_months', models.PositiveIntegerField(default=60)),
                ('interest_type', models.CharField(choices=[('flat', 'Flat'), ('reducing', 'Reducing Balance'), ('other', 'Other')], default='flat', max_length=20)),
                ('requires_savings', models.BooleanField(default=False)),
                ('minimum_savings_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('processing_fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loantype'),
        ),
        migrations.CreateModel(
            name='OldLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursed_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off')], max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borrowers.borrower')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='borrowers.borrowergroup')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('missed', 'Missed'), ('rolled_over', 'Rolled Over'), ('defaulted', 'Defaulted')], default='pending', max_length=15)),
                ('installment_number', models.PositiveIntegerField()),
                ('is_group', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('missed', 'Missed'), ('rolled_over', 'Rolled Over'), ('defaulted', 'Defaulted')], default='paid', max_length=15)),
                ('is_rollover', models.BooleanField(default=False)),
                ('group_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loans.grouploanmember')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='borrowers.borrower')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.repaymentschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('cleared', 'Cleared')], default='applied', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='loans.loan')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='loans.repaymentschedule')),
            ],
        ),
        migrations.CreateModel(
            name='MissedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missed_date', models.DateField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borrowers.borrower')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_payments', to='loans.repaymentschedule')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenOffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_off_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='written_off', to='loans.loan')),
                ('written_off_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_number'], name='loans_loan_loan_nu_9c0f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower'], name='loans_loan_borrowe_4ce53f_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['application_date'], name='loans_loan_applica_4a1ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['disbursement_date'], name='loans_loan_disburs_33922a_idx'),
        ),
    ]


