# Generated by Django 5.2.3 on 2025-08-07 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repaymentschedule',
            options={'ordering': ['loan', 'installment_number']},
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='repaymentschedule',
            unique_together={('loan', 'installment_number')},
        ),
        migrations.CreateModel(
            name='LoanPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('late_payment', 'Late Payment'), ('missed_payment', 'Missed Payment'), ('default', 'Default'), ('other', 'Other')], default='late_payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('cleared', 'Cleared')], default='applied', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='loans.loan')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='loans.repaymentschedule')),
            ],
            options={
                'verbose_name_plural': 'Loan Penalties',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('loans.loanpenalty',),
        ),
    ]


