# Generated by Django 5.2.3 on 2025-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_collateral_name_loan_collateral_withheld_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='repayment_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20),
        ),
    ]


