# Generated by Django 5.2.3 on 2026-01-13 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_loan_rejected_by_loan_rejection_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="assigned_recovery_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="Officer assigned to handle NPL recovery",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_npl_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="is_npl",
            field=models.BooleanField(
                default=False,
                help_text="Whether this loan is classified as non-performing",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="last_recovery_contact_date",
            field=models.DateField(
                blank=True, help_text="Date of last contact for recovery", null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_recovery_action_date",
            field=models.DateField(
                blank=True,
                help_text="Scheduled date for next recovery action",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="npl_category",
            field=models.CharField(
                choices=[
                    ("performing", "Performing"),
                    ("watch", "Watch (90-180 days)"),
                    ("substandard", "Substandard (180-270 days)"),
                    ("doubtful", "Doubtful (270-365 days)"),
                    ("loss", "Loss (365+ days)"),
                ],
                default="performing",
                help_text="NPL classification based on days overdue",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="npl_classification_date",
            field=models.DateField(
                blank=True, help_text="Date when loan was classified as NPL", null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="npl_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes regarding NPL status and recovery efforts",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="npl_provision_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Provision amount set aside for potential loss",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="npl_recovery_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount recovered from NPL",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="npl_status",
            field=models.CharField(
                choices=[
                    ("none", "Not Classified"),
                    ("under_review", "Under Review"),
                    ("recovery_active", "Active Recovery"),
                    ("restructured", "Restructured"),
                    ("legal_action", "Legal Action"),
                    ("write_off_pending", "Write-off Pending"),
                    ("written_off", "Written Off"),
                ],
                default="none",
                help_text="Current status of NPL resolution",
                max_length=20,
            ),
        ),
    ]


