# Generated by Django 5.2.3 on 2026-01-14 17:16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowers", "0001_initial"),
        ("loans", "0006_loan_assigned_recovery_officer_loan_is_npl_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grouploan",
            options={
                "verbose_name": "Group Loan",
                "verbose_name_plural": "Group Loans",
            },
        ),
        migrations.AlterModelOptions(
            name="grouploanmember",
            options={
                "verbose_name": "Group Loan Member",
                "verbose_name_plural": "Group Loan Members",
            },
        ),
        migrations.AlterModelOptions(
            name="loandisbursement",
            options={
                "ordering": ["-disbursement_date"],
                "verbose_name": "Loan Disbursement",
                "verbose_name_plural": "Loan Disbursements",
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="total_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="grouploanmember",
            name="responsibility_share",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("due", "Due"),
                    ("paid", "Paid"),
                    ("partial", "Partially Paid"),
                    ("missed", "Missed"),
                    ("rolled_over", "Rolled Over"),
                    ("defaulted", "Defaulted"),
                ],
                default="paid",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="repaymentschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("due", "Due"),
                    ("paid", "Paid"),
                    ("partial", "Partially Paid"),
                    ("missed", "Missed"),
                    ("rolled_over", "Rolled Over"),
                    ("defaulted", "Defaulted"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouploanmember",
            unique_together={("group_loan", "borrower")},
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["is_npl", "npl_category"], name="loans_loan_is_npl_4af5cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentschedule",
            index=models.Index(
                fields=["loan", "due_date"], name="loans_repay_loan_id_c6e76a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentschedule",
            index=models.Index(
                fields=["status", "due_date"], name="loans_repay_status_eb8bd0_idx"
            ),
        ),
    ]
