# Generated by Django 5.2.3 on 2026-04-13 16:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_alter_grouploan_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="amount_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Approved loan amount must be greater than zero",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="collateral_withheld",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Withheld collateral amount must be non-negative",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="collateral_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Collateral value must be non-negative",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="outstanding_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Outstanding balance must be non-negative",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="processing_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Processing fee must be non-negative",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total loan amount must be non-negative",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_interest",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total interest amount must be non-negative",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total paid amount must be non-negative",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentschedule",
            index=models.Index(
                fields=["due_date"], name="loans_repay_due_dat_7543ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentschedule",
            index=models.Index(fields=["status"], name="loans_repay_status_ed45e9_idx"),
        ),
    ]
