# Generated by Django 5.2.3 on 2026-04-13 16:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowers", "0002_alter_borrower_branch_alter_borrowergroup_branch"),
        ("loans", "0008_add_constraints_and_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repayment",
            options={
                "ordering": ["-payment_date"],
                "verbose_name": "Repayment",
                "verbose_name_plural": "Repayments",
            },
        ),
        migrations.AlterField(
            model_name="repayment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount paid (must be positive)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="group_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Group member if this is for a group loan",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="loans.grouploanmember",
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="is_rollover",
            field=models.BooleanField(
                default=False,
                help_text="Whether this payment was rolled over from previous period",
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Borrower who made the payment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="borrowers.borrower",
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="payment_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date when payment was received",
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="received_by",
            field=models.ForeignKey(
                help_text="Staff member who received the payment",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="schedule",
            field=models.ForeignKey(
                help_text="The installment this payment is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repayments",
                to="loans.repaymentschedule",
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("due", "Due"),
                    ("paid", "Paid"),
                    ("partial", "Partially Paid"),
                    ("missed", "Missed"),
                    ("rolled_over", "Rolled Over"),
                    ("defaulted", "Defaulted"),
                ],
                default="paid",
                help_text="Status of this payment record",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="repaymentschedule",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount due for this installment",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="repaymentschedule",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid towards this installment",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
