# Generated by Django 5.2.3 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0009_improve_model_validation_and_constants"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="completion_date",
            field=models.DateField(
                blank=True,
                help_text="Date when loan was fully paid/completed",
                null=True,
            ),
        ),
    ]
