# Generated by Django 5.2.3 on 2026-04-17 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0010_loan_completion_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="is_rejection_reversed",
            field=models.BooleanField(
                default=False, help_text="Whether rejection has been reversed"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="rejection_reversed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reversed the rejection",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_loan_rejections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="reversal_reason",
            field=models.TextField(
                blank=True, help_text="Reason for reversing the rejection", null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="reversed_rejection_date",
            field=models.DateField(
                blank=True, help_text="Date when rejection was reversed", null=True
            ),
        ),
    ]
