# Generated by Django 5.2.3 on 2026-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0012_alter_loan_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="repayment_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("every_three_days", "Every 3 Days"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("annually", "Annually"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
