# Generated by Django 5.2.3 on 2026-04-18 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowers", "0003_borrower_nickname"),
        ("loans", "0013_alter_loan_repayment_frequency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("loan_created", "Loan Created"),
                            ("loan_approved", "Loan Approved"),
                            ("loan_rejected", "Loan Rejected"),
                            ("loan_disbursed", "Loan Disbursed"),
                            ("loan_completed", "Loan Completed"),
                            ("loan_defaulted", "Loan Defaulted"),
                            ("loan_written_off", "Loan Written Off"),
                            ("repayment_recorded", "Repayment Recorded"),
                            ("repayment_partial", "Partial Payment Recorded"),
                            ("repayment_rollover", "Payment Rolled Over"),
                            ("schedule_generated", "Schedule Generated"),
                            ("schedule_marked_paid", "Schedule Marked as Paid"),
                            ("penalty_applied", "Penalty Applied"),
                            ("penalty_cleared", "Penalty Cleared"),
                            ("loan_edited", "Loan Edited"),
                            ("collection_contact", "Collection Contact Recorded"),
                            ("recovery_action", "Recovery Action Recorded"),
                            ("system_action", "System Action"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the action"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data about the activity (before/after values, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "is_error",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this activity logged an error or issue",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="borrowers.borrower",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="loans.loan",
                    ),
                ),
                (
                    "repayment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="loans.repayment",
                    ),
                ),
                (
                    "repayment_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="loans.repaymentschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="loans_activ_action_1d7eb0_idx",
                    ),
                    models.Index(
                        fields=["loan", "-created_at"],
                        name="loans_activ_loan_id_12b23a_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="loans_activ_user_id_a35cab_idx",
                    ),
                    models.Index(
                        fields=["borrower", "-created_at"],
                        name="loans_activ_borrowe_aa6c8a_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="loans_activ_created_e40f86_idx"
                    ),
                ],
            },
        ),
    ]
