# Generated by Django 5.2.3 on 2026-04-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0015_alter_loan_repayment_frequency_legacy_evey"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS loans_activitylog",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="ActivityLog",
                ),
            ],
        ),
    ]
