# Generated by Django 5.2.3 on 2026-04-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0016_delete_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="loan_type",
        ),
    ]
