# Generated by Django 5.2.3 on 2026-04-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0017_remove_loan_loan_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoanType",
        ),
    ]
