# Generated by Django 5.2.3 on 2026-05-11 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0018_delete_loantype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "ordering": ["-application_date", "-created_at"],
                "permissions": [
                    ("can_reject_loan", "Can reject pending loans"),
                    ("can_refer_loan", "Can refer pending loans"),
                    ("can_reverse_rejection", "Can reverse rejected loans"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("referred", "Referred"),
                    ("disbursed", "Disbursed"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("defaulted", "Defaulted"),
                    ("written_off", "Written Off"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="oldloan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("referred", "Referred"),
                    ("disbursed", "Disbursed"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("defaulted", "Defaulted"),
                    ("written_off", "Written Off"),
                ],
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="LoanReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referral_reason", models.TextField()),
                (
                    "referral_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resubmitted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="loans.loan",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_referrals_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resubmitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_referrals_resubmitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Referral",
                "verbose_name_plural": "Loan Referrals",
                "ordering": ["-referral_date"],
                "indexes": [
                    models.Index(
                        fields=["loan", "-referral_date"],
                        name="loans_loanr_loan_id_d54772_idx",
                    ),
                    models.Index(
                        fields=["referred_to", "is_resolved"],
                        name="loans_loanr_referre_68deca_idx",
                    ),
                ],
            },
        ),
    ]
