# Generated by Django 5.2.3 on 2026-05-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0019_alter_loan_options_alter_loan_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "ordering": ["-application_date", "-created_at"],
                "permissions": [
                    ("can_reject_loan", "Can reject pending loans"),
                    ("can_reverse_rejection", "Can reverse rejected loans"),
                ],
            },
        ),
    ]
