# Generated by Django 5.2.3 on 2026-04-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_4e3567_idx",
            old_name="notificatio_recipie_9f26c5_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_created_46ad24_idx",
            old_name="notificatio_created_aa27fe_idx",
        ),
    ]
